# -*- coding: utf-8 -*-
"""ANN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mX4z7EzvNFMu_tRVI3zcdbioFI_YtAcQ
"""



import numpy as np
# Step 1: Define activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_derivative(x):
    return x * (1 - x)
# Step 2: Define input dataset (XOR)
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
# Expected output
y = np.array([[0],
              [1],
              [1],
              [0]])
# Step 3: Initialize weights and bias
np.random.seed(42)
input_neurons = 2
hidden_neurons = 2
output_neurons = 1
W1 = np.random.uniform(size=(input_neurons, hidden_neurons))
W2 = np.random.uniform(size=(hidden_neurons, output_neurons))
# Step 4: Training parameters
learning_rate = 0.5
epochs = 10000
# Step 5: Training using Backpropagation
for epoch in range(epochs):
    # -------- Forward Propagation --------
    hidden_input = np.dot(X, W1)
    hidden_output = sigmoid(hidden_input)
    final_input = np.dot(hidden_output, W2)
    final_output = sigmoid(final_input)
    # -------- Error Calculation --------
    error = y - final_output
    # -------- Backward Propagation --------
    d_output = error * sigmoid_derivative(final_output)
    d_hidden = d_output.dot(W2.T) * sigmoid_derivative(hidden_output)
    # -------- Update Weights --------
    W2 += hidden_output.T.dot(d_output) * learning_rate
    W1 += X.T.dot(d_hidden) * learning_rate
# Step 6: Testing the trained ANN
print("Input:")
print(X)
print("\nExpected Output:")
print(y)
print("\nPredicted Output after Training:")
print(np.round(final_output))