# -*- coding: utf-8 -*-
"""Candidate-Elimination algorithm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHnE08krmxCWElQWnoxwq_NSCpW9KjKY
"""



import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix
# Step 2: Load dataset
iris = load_iris()
X = iris.data      # Features
y = iris.target    # Target labels
# Step 3: Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
# Step 4: Create Naïve Bayes classifier
nb = GaussianNB()
# Step 5: Train the model
nb.fit(X_train, y_train)
# Step 6: Predict on test data
y_pred = nb.predict(X_test)
# Step 7: Calculate Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy of Naïve Bayes:", accuracy)
# Step 8: Display Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)