# -*- coding: utf-8 -*-
"""ESTIMATION MAXIMIZATION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBA3ptw0B3bY3GD3E4hL1tR_Cm4KkJ0e
"""



# Step 1: Import required libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.mixture import GaussianMixture
# Step 2: Create sample data (unsupervised)
np.random.seed(42)
X1 = np.random.normal(loc=2, scale=0.5, size=(100, 2))
X2 = np.random.normal(loc=6, scale=0.5, size=(100, 2))
X = np.vstack((X1, X2))
# Step 3: Create Gaussian Mixture Model (EM Algorithm)
gmm = GaussianMixture(n_components=2, random_state=42)
# Step 4: Fit the model (Expectation + Maximization steps)
gmm.fit(X)
# Step 5: Predict cluster labels
labels = gmm.predict(X)
# Step 6: Get cluster means
means = gmm.means_
# Step 7: Display results
print("Cluster Means:")
print(means)
# Step 8: Plot the clustered data
plt.scatter(X[:, 0], X[:, 1], c=labels)
plt.scatter(means[:, 0], means[:, 1], marker='X', s=200)
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.title("Expectation-Maximization using GMM")
plt.show()