# -*- coding: utf-8 -*-
"""FIND S

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lVZebeMOn2D-NnD9pGRqEjRwhvEgaLud
"""



import pandas as pd
data = {
    "Sky": ["Sunny", "Sunny", "Rainy", "Sunny"],
    "AirTemp": ["Warm", "Warm", "Cold", "Warm"],
    "Humidity": ["Normal", "High", "High", "High"],
    "Wind": ["Strong", "Strong", "Strong", "Weak"],
    "Water": ["Warm", "Warm", "Warm", "Warm"],
    "Forecast": ["Same", "Same", "Change", "Same"],
    "EnjoySport": ["Yes", "Yes", "No", "Yes"]
}
df = pd.DataFrame(data)
print("Training Dataset:\n")
print(df)
# Step 2: FIND-S Algorithm
def find_s_algorithm(training_data):
    # Initialize hypothesis with most specific values
    hypothesis = ["0"] * (len(training_data.columns) - 1)
    for index, row in training_data.iterrows():
        if row[-1] == "Yes":  # Consider only positive examples
            for i in range(len(hypothesis)):
                if hypothesis[i] == "0":
                    hypothesis[i] = row[i]
                elif hypothesis[i] != row[i]:
                    hypothesis[i] = "?"
    return hypothesis
# Step 3: Run Algorithm
final_hypothesis = find_s_algorithm(df)
# Step 4: Display Result
print("\nMost Specific Hypothesis Found by FIND-S:\n")
print(final_hypothesis)