# -*- coding: utf-8 -*-
"""KNN Implementation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZKknRWCHbqq4u1vhvkON8rPIXNjir6ww
"""

# K-Nearest Neighbours (K-NN) Implementation in Python
# Works perfectly in Google Colab
# Step 1: Import required libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# Step 2: Load dataset
iris = load_iris()
X = iris.data      # Features
y = iris.target    # Labels
# Step 3: Split dataset into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
# Step 4: Create KNN classifier
k = 5
knn = KNeighborsClassifier(n_neighbors=k)
# Step 5: Train the model
knn.fit(X_train, y_train)
# Step 6: Make predictions
y_pred = knn.predict(X_test)
# Step 7: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
# Step 8: Visualize accuracy for different K values
k_values = range(1, 11)
accuracies = []
for k in k_values:
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    accuracies.append(accuracy_score(y_test, pred))
plt.plot(k_values, accuracies, marker='o')
plt.xlabel("K value")
plt.ylabel("Accuracy")
plt.title("K-NN Accuracy for Different K Values")
plt.grid(True)
plt.show()

# Step 1: Import required libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
# Step 2: Create sample dataset
# X = independent variable, y = dependent variable
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(-1, 1)
y = np.array([2, 4, 5, 4, 5, 7, 8, 9, 10, 12])
# Step 3: Create Linear Regression model
model = LinearRegression()
# Step 4: Train the model
model.fit(X, y)
# Step 5: Make predictions
y_pred = model.predict(X)
# Step 6: Display model parameters
print("Slope (m):", model.coef_[0])
print("Intercept (c):", model.intercept_)
# Step 7: Evaluate the model
mse = mean_squared_error(y, y_pred)
r2 = r2_score(y, y_pred)
print("Mean Squared Error:", mse)
print("R² Score:", r2)
# Step 8: Plot the regression line
plt.scatter(X, y)
plt.plot(X, y_pred)
plt.xlabel("X")
plt.ylabel("y")
plt.title("Linear Regression")
plt.show()