# -*- coding: utf-8 -*-
"""Linear Regression vs Polynomial Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPRFgJdI4UXCslnSutwiSlO-oLESC0Br
"""



# Linear Regression vs Polynomial Regression
# Comparison using Python
# Works in Google Colab
# Step 1: Import required libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, r2_score
# Step 2: Create sample dataset
# X = input feature, y = output
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(-1, 1)
y = np.array([2, 4, 5, 4, 5, 7, 8, 9, 10, 12])
# ---------------- Linear Regression ----------------
lr = LinearRegression()
lr.fit(X, y)
y_pred_lr = lr.predict(X)
# Linear Regression metrics
mse_lr = mean_squared_error(y, y_pred_lr)
r2_lr = r2_score(y, y_pred_lr)
# ---------------- Polynomial Regression ----------------
poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)
pr = LinearRegression()
pr.fit(X_poly, y)
y_pred_pr = pr.predict(X_poly)
# Polynomial Regression metrics
mse_pr = mean_squared_error(y, y_pred_pr)
r2_pr = r2_score(y, y_pred_pr)
# ---------------- Results ----------------
print("Linear Regression Results")
print("MSE:", mse_lr)
print("R² Score:", r2_lr)
print("\nPolynomial Regression Results")
print("MSE:", mse_pr)
print("R² Score:", r2_pr)
# ---------------- Graph Comparison ----------------
plt.scatter(X, y)
plt.plot(X, y_pred_lr, label="Linear Regression")
plt.plot(X, y_pred_pr, label="Polynomial Regression")
plt.xlabel("X")
plt.ylabel("y")
plt.title("Linear vs Polynomial Regression")
plt.legend()
plt.show()