# -*- coding: utf-8 -*-
"""Linear Regression (LR) Implementation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zsROLF10jfyPwvkzFcighDb8rPn9RoI
"""



# Step 1: Import required libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
# Step 2: Create sample dataset
# X = independent variable, y = dependent variable
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(-1, 1)
y = np.array([2, 4, 5, 4, 5, 7, 8, 9, 10, 12])
# Step 3: Create Linear Regression model
model = LinearRegression()
# Step 4: Train the model
model.fit(X, y)
# Step 5: Make predictions
y_pred = model.predict(X)
# Step 6: Display model parameters
print("Slope (m):", model.coef_[0])
print("Intercept (c):", model.intercept_)
# Step 7: Evaluate the model
mse = mean_squared_error(y, y_pred)
r2 = r2_score(y, y_pred)
print("Mean Squared Error:", mse)
print("R² Score:", r2)
# Step 8: Plot the regression line
plt.scatter(X, y)
plt.plot(X, y_pred)
plt.xlabel("X")
plt.ylabel("y")
plt.title("Linear Regression")
plt.show()